config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'
  get 'admin/resumes' => 'admin#resumes', as: 'admin_resume'
  get 'admin/students' => 'admin#students', as: 'admin_students'
  get 'admin/companies' => 'admin#companies', as: 'admin_companies'

  root 'pages#homepage'

  get 'past_events' => 'pages#past_events', as: 'past_events'

  resources :students, only: [:new, :create]
  resources :companies, only: [:new, :create]

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title MIT Energy Career Fair 2018
    = stylesheet_link_tag :application, :media => "all"
    = csrf_meta_tags
  %body{id: "#{controller_name}_#{action_name}"}
    - if flash[:success] or flash[:alert]
      %script= "alert('#{flash[:success] or flash[:alert]}'); "
    %ul#nav_left
      %li= link_to 'Sponsors', '#intro'
      %li= link_to 'FAQ', '#faq'
      %li= link_to 'Our Team', '#team'
      %li= link_to 'Past Event', past_events_path
    %ul#nav
      %li{class: @current == 'Homepage' ? 'current' : ''}= link_to 'Homepage', root_path
      %li{class: @current == 'Students' ? 'current' : ''}= link_to 'Students', new_student_path
      %li{class: @current == 'Employers' ? 'current' : ''}= link_to 'Employers', new_company_path
    = yield
    %script{src: 'https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js'}
    %script{src: 'https://cdnjs.cloudflare.com/ajax/libs/galleria/1.4.5/galleria.min.js'}
    = javascript_include_tag :application